#!/usr/bin/perl

# Generates an HTTP/1.1 request suitable for sending to the Intel Attestation
# Servers.
#

use strict;
use Getopt::Std;
use vars qw( $Prog );
use HTTP::Request;

my (%opt, $version, $quote, $clen, $req);
my (%body);

($Prog= $0)=~ s#^.*/##;

&usage unless &getopts('i:v:h', \%opt);
&usage if $opt{h};

$version= $opt{v} || 2;

if ( $opt{'i'} ) {
	my $id= $opt{'i'};
	$req= new HTTP::Request('GET', "/attestation/sgx/v${version}/report/$id");
	print $req->as_string;
	exit(0);
}

while(<>) {
	chomp;
	my ($field, $data)= split(" ", $_);
	$body{$field}= $data;
}

$quote= $body{'quote'};
$clen= 22+length($quote);
$clen+= 11+length($body{'nonce'}) if (exists $body{'nonce'});

print<<EOM;
POST /attestation/sgx/v${version}/report
Content-Type: application/json
Content-Length: $clen

EOM

printf('{"isvEnclaveQuote":"%s"', $quote);
if ( exists($body{'nonce'}) ) {
	printf(',"nonce":"%s"', $body{'nonce'})
}
print "\}\n\n";

0;

sub usage {
        print STDERR <<EOM;
usage: $Prog [ -i id ] [ -v apiversion ]
EOM
        exit 1;
}

