#! /bin/sh

export LD_LIBRARY_PATH=/usr/local/lib

SPID="-S ../ias-ra-data/spid/plse-dev.spid"
CERT="-C ./dev.pem"

CMD="./sp -d -v $SPID $CERT"

echo "Running: $CMD"

socat TCP4-LISTEN:7777,fork,reuseaddr EXEC:"$CMD $SPID",nofork

